### ISSUE TITLE
Latest ci version can`t be loaded

### ISSUE THREAD

**Issue by TerThesz** [ViaVersion/ViaRewind#217]
Using: Spigotmc 1.12.2
Error:
Error occurred while enabling ViaBackwards v3.1.1 (Is it up to date?)
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.protocol.Protocol.<init>(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Z)V
        at nl.matsv.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:21) ~[?:?]
        at nl.matsv.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:31) ~[?:?]
        at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:68) ~[?:?]
        at nl.matsv.viabackwards.BukkitPlugin.onEnable(BukkitPlugin.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:751) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Gerrygames** [comment]
> Error occurred while enabling ViaBackwards
Outdated ViaBackwards or ViaVersion
