### ISSUE TITLE
 Could not convert component to legacy text

### ISSUE THREAD

**Issue by bobhenl** [ViaVersion/ViaRewind#230]
Hi, I'm getting this issue on 1.16.4 server with viarewind:
```
[16:27:29] [Netty Epoll Server IO #1/WARN]: [ViaRewind] Could not convert component to legacy text: wveb54yn4y6y6hy6hb54yb5436by5346y3b4yb343yb453by45b34y5by34yb543yb54y5 h3y4h97,i567yb64t5vr2c43rc434v432tvt4tvybn4n6n57u6u57m6m6678mi68,867,79o,o97o,978iun7yb65453v4tyv34t4t3c2cc423rc334tcvtvt43tv45tvt5t5v43tv5345tv43tv5355vt5t3tv5t533v5t45tv43vt4355t54fwveb54yn4y6y6hy6hb54yb5436by5346y3b4yb343yb453by45b34y5by34yb543yb54y5 h3y4h97,i567yb64t5vr2c43rc434v432tvt4tvybn4n6n57u6u57m6m6678mi68,867,79o,o97o,978iun7yb65453v4tyv34t4t3c2cc423rc334tcvtvt43tv45tvt5t5v43tv5345tv43tv5355vt5t3tv5t533v5t45tv43vt4355t54fwveb54yn4y6y6hy6hb54yb5436by5346y3b4yb343yb453by45b34y5by34yb543yb54y5 h3y4h97,i567yb64t5
us.myles.viaversion.libs.gson.JsonSyntaxException: us.myles.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 73 path $
	at us.myles.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:66) ~[?:?]
	at us.myles.viaversion.libs.gson.JsonParser.parseString(JsonParser.java:47) ~[?:?]
	at us.myles.viaversion.libs.gson.JsonParser.parse(JsonParser.java:98) ~[?:?]
	at us.myles.viaversion.libs.bungeecordchat.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[?:?]
	at de.gerrygames.viarewind.utils.ChatUtil.jsonToLegacy(ChatUtil.java:17) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$23$1.handle(PlayerPackets.java:731) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395) ~[?:?]
	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor204.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-313]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.16.4.jar:git-Paper-313]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.4.jar:git-Paper-313]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: us.myles.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 73 path $
	at us.myles.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1564) ~[?:?]
	at us.myles.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1405) ~[?:?]
	at us.myles.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:543) ~[?:?]
	at us.myles.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:426) ~[?:?]
	at us.myles.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:61) ~[?:?]
	... 50 more
```
It spammed really Xx times, maybe 20 times...
Then player got kicked:
[16:27:37] [Server thread/INFO]: GigaAdamYT lost connection: Internal Exception: java.lang.IllegalStateException: PlayerKickEvent may only be triggered synchronously. My idea is that player kicked on one of these banner (30s before he clicked on the first, and I think then he clicked on the second/third one probably https://pastebin.com/wBdzzCLB (made in commands.yml)
Here's viaversion dump: https://dump.viaversion.com/a39c03b79207d5638da9fcf3aa03f3ec194f92e1ec4c23c811662e22cb09fa1b

Versions:
![image](https://user-images.githubusercontent.com/18662086/101270067-8e1e8c00-3775-11eb-88f9-27d010ef1173.png)

Probably happened after player clicked on banner with this text, but not sure, cause he clicked on this banner 30s before.

**Comment by Gerrygames** [comment]
That's a player sending invalid book data.
