### ISSUE TITLE
NoSuchFieldError: DOUBLE

### ISSUE THREAD

**Issue by mibby** [ViaVersion/ViaRewind#266]
ViaVersion-DEV 423
ViaBackwards-DEV 253
ViaRewind 90

Quick forward. Breaking with latest ViaVersion-DEV builds?

```
[05:19:50] [Server thread/INFO]: [ViaRewind] Enabling ViaRewind v1.5.3
[05:19:50] [Server thread/ERROR]: Error occurred while enabling ViaRewind v1.5.3 (Is it up to date?)
java.lang.NoSuchFieldError: DOUBLE
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.EntityPackets$5.registerMap(EntityPackets.java:209) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.<init>(PacketRemapper.java:17) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.EntityPackets$5.<init>(EntityPackets.java:197) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.EntityPackets.register(EntityPackets.java:197) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.Protocol1_8TO1_9.registerPackets(Protocol1_8TO1_9.java:58) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:54) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:42) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.Protocol1_8TO1_9.<init>(Protocol1_8TO1_9.java:28) ~[?:?]
	at de.gerrygames.viarewind.api.ViaRewindPlatform.init(ViaRewindPlatform.java:21) ~[?:?]
	at de.gerrygames.viarewind.BukkitPlugin.onEnable(BukkitPlugin.java:14) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:207) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3068/1596017970.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[05:19:50] [Server thread/INFO]: [ViaRewind] Disabling ViaRewind v1.5.3```
```

**How can we reproduce it?**
1. Use latest DEV builds of all Via plugins.

**Expected behaviour**
No error.

**ViaVersion Dump:**
https://dump.viaversion.com/92a174cfd080193bf5625a52b7dbbb02f5717423ec3de9cc870428bdaeb367c5

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by KennyTV** [comment]
Use ViaRewind dev builds.

**Comment by mibby** [comment]
Can you merge master changes into the dev branch?
