### ISSUE TITLE
1.7.10 Client Crash - PlayerPackets Unable... found JsonElement

### ISSUE THREAD

**Issue by ObedMz** [ViaVersion/ViaRewind#275]
**Describe the bug, provide any errors**
Hi, i have a server running in 1.16.5 version, and i allow my players to join since 1.7.10, the problem is when they died, their client just crash with the next log:
The game crashed whilst unexpected error Error: java.lang.ArrayIndexOutOfBoundsException: 4 Exit Code: -1

The server just show this error:
[ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x38->0x38

**How can we reproduce it?**
1. server 1.16.5, viaversion, viabackwards, viarewind
1. Login on 1.7.10'
2. Die
3. Hey, your client just crash! 

**Expected behaviour**
I just expected that my players respawn into the spawn world.

**Screenshots**
https://media.discordapp.net/attachments/316208160232701955/810204159538233364/unknown.png?width=1037&height=215

**ViaVersion Dump:**
- https://dump.viaversion.com/b4ff224de1143d5a6b74401356183c45b0a0b950538b1ab522f70605732204c7

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
I just Travertine for bungeecord.
Paper 1.16.5 
Plugins:
 Viaversion, ViaBackWards, ViaRewind

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [X] If applicable, I have included a paste (not a screenshot) of the error
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by MacacoLew** [comment]
bump

**Comment by creeper123123321** [comment]
````Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$10$1 (Anonymous), Packet ID: 56, Source 1: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$10 (Anonymous)}
Actual Error: 
Caused by: java.io.IOException: Unable to read type String, found JsonElement
	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:182) ~[viaaas-master.jar:?]
	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$10$1.handle(PlayerPackets.java:396) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:41) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:153) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:429) ~[viaaas-master.jar:?]
	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:106) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:493) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:479) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:97) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:437) ~[viaaas-master.jar:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:423) ~[viaaas-master.jar:?]
	at com.github.creeper123123321.viaaas.handler.ViaCodec.decode(ViaCodec.kt:20) ~[viaaas-master.jar:?]
	at com.github.creeper123123321.viaaas.handler.ViaCodec.decode(ViaCodec.kt:10) ~[viaaas-master.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[viaaas-master.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[viaaas-master.jar:?]
	... 36 more
``` demo.spongepowered.org server

**Comment by creeper123123321** [comment]
Try latest -DEV build from ci.viaversion.com. should be fixed
