### ISSUE TITLE
ERROR IN Protocol1_16_4To1_17 IN REMAP OF SPAWN_PARTICLE (0x24)

### ISSUE THREAD

**Issue by Folas1337** [ViaVersion/ViaRewind#328]
**Describe the bug, provide any errors**
[21:44:27] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF SPAWN_PARTICLE (0x24)
[21:44:27] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[21:44:27] [Netty Epoll Server IO #1/WARN]: {Type: Float, Data: [Pair{Type|Integer, 15}, Pair{Type|Boolean, true}, Pair{Type|Double, 926.5}, Pair{Type|Double, 62.0}, Pair{Type|Double, -44.5}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 1}, Pair{Type|Float, 0.99215686}, Pair{Type|Float, 0.9607843}, Pair{Type|Float, 0.9019608}, Pair{Type|Float, 1.0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$3 (Anonymous), Packet ID: 34}
[21:44:27] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[21:44:27] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[21:44:27] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template

**How can we reproduce it?**
1. Login on 1.16
2. Join the server
3. The server sends an error and won't let you join

**Expected behaviour**
Server lets you join fine.

**ViaVersion Dump:**
https://dump.viaversion.com/77ef12d39f3e37c2d9e06b3dece63835e6555edb3489d083add9010d3b5902c8

**Additional server info**
I am using Waterfall and here's my list of plugins:
PlaceholderAPI, UltimateAutoRestart, ArmorStandEditor, Votifier, MaSuiteCore, JoinMessage, ViaVersion, ViaBackwards, LuckPerms, MaSuiteWarps, MaSuiteTeleports, ProtocolLib, Vault, dynmap, WorldEdit, Essentials, AntiCheatReloaded, IllegalStack, EpicHeads, AsyncWorldEdit, MultiChat, TimeIsMoney, SuperbVote, PlotSquared, WorldGuard, Multiverse-Core, DiscordSRV, WorldGuardExtraFlags, CMILib, SelectionVisualizer

Using ViaBackwards 4.0.0

**Checklist** (mark with [X] to check)
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [x] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Folas1337** [comment]
I narrowed the problem down to PlotSquared, apparently when you claim a plot it seems to create particles which do not translate to 1.16, unfortunate :(

**Comment by FormallyMyles** [comment]
You checked that you tried a dev build from ci.viaversion.com, but your dump doesn't prove so? Can you try the builds from there?

**Comment by Folas1337** [comment]
> You checked that you tried a dev build from ci.viaversion.com, but your dump doesn't prove so? Can you try the builds from there?

I should be running a snapshot and I think I can also see that in the dump but does a dev version of ViaRewind exist or is that not really necessary? I'm a little confused, sorry... can you link the me the exact file that I would have to download to be sure we're talking about the same thing?

**Comment by FormallyMyles** [comment]
https://ci.viaversion.com/job/ViaBackwards/

**Comment by Folas1337** [comment]
Oh dang I didn't see the tabs on top where you could also get dev version of ViaBackwards.
This is solved, sorry to have bothered you and thanks for the very, VERY quick reply <3
