### ISSUE TITLE
1.8.9 disconnect InventoryPacket

### ISSUE THREAD

**Issue by htbrown** [ViaVersion/ViaRewind#329]
### `/viaversion dump` Output

https://dump.viaversion.com/d374370fa912b69262b91839848cfd6e56c87a457eb55c94bd6bc83ffaf0f7a8

### Console Error

```
[thehtbrown] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104
```

### Bug Description

Tested on 1.8.9, installed on a Waterfall server (ViaVersion, ViaBackwards, ViaRewind).

When a player joins on 1.8.9 they are kicked.

### Steps to Reproduce

1. Install latest dev version of ViaVersion, ViaBackwards and ViaRewind on a Waterfall (build 436) server.
2. Try to connect on a 1.8.9 client (not sure if it happens on any others).

### Expected Behavior

Player shouldn't get kicked from the server.

### Additional Server Info

Installed on Waterfall with a custom plugin that doesn't affect it.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by creeper123123321** [comment]
```java
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
Actual Error: 
Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140) ~[viaaas.jar:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47) ~[viaaas.jar:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper$$Lambda$150/0000000038E29AF0.handle(Unknown Source) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[viaaas.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287) ~[viaaas.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350) ~[viaaas.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338) ~[viaaas.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[viaaas.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117) ~[viaaas.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289) ~[viaaas.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268) ~[viaaas.jar:?]
        at com.viaversion.aas.handler.ViaCodec.decode(ViaCodec.kt:20) ~[viaaas.jar:?]
        at com.viaversion.aas.handler.ViaCodec.decode(ViaCodec.kt:10) ~[viaaas.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[viaaas.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[viaaas.jar:?]
        ... 36 more

```

**Comment by creeper123123321** [comment]
may be fixed by https://github.com/ViaVersion/ViaRewind/commit/d6e905dfe1eea94fbb08392885965e27fa884252

**Comment by creeper123123321** [comment]
fixed in -DEV builds
