### ISSUE TITLE
Error open villager rename

### ISSUE THREAD

**Issue by franxyk** [ViaVersion/ViaRewind#338]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://paste.gg/ the error?

**How can we reproduce it?**
1. Login on 1.7.X client
2. Click on villager rename to open trade gui.

**Expected behaviour**
That the error does not appear and the name of the villager appears.

**Screenshots**
+

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
[14:15:54] [Netty Epoll Server IO #1/WARN]: [ViaRewind] Could not convert component to legacy text: {"insertion":"34cf770e-4c1a-4704-97af-c6f71df2589e","hoverEvent":{"action":"show_entity","value":"{name:\"Villager\",id:\"34cf770e-4c1a-4704-97af-c6f71df2589e\",type:\"Villager\"}"},"translate":"entity.Villager.shepherd"}
java.lang.UnsupportedOperationException
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:194) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:156) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:98) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:53) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:932) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1003) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:161) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:75) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:55) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:932) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:897) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:846) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:817) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:101) ~[ViaVersion.jar:?]
	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:44) ~[ViaVersion.jar:?]
	at de.gerrygames.viarewind.utils.ChatUtil.jsonToLegacy(ChatUtil.java:17) [ViaRewind-2.0.1.jar:git-ViaRewind-2.0.1:a53d82f]
	at de.gerrygames.viarewind.utils.ChatUtil.jsonToLegacy(ChatUtil.java:32) [ViaRewind-2.0.1.jar:git-ViaRewind-2.0.1:a53d82f]
	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.InventoryPackets$1$1.handle(InventoryPackets.java:40) [ViaRewind-2.0.1.jar:git-ViaRewind-2.0.1:a53d82f]
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) [ViaVersion.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287) [ViaVersion.jar:?]
	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:91) [ViaRewind-2.0.1.jar:git-ViaRewind-2.0.1:a53d82f]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350) [ViaVersion.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338) [ViaVersion.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) [ViaVersion.jar:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117) [ViaVersion.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290) [ViaVersion.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269) [ViaVersion.jar:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90) [ViaVersion.jar:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83) [ViaVersion.jar:?]
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262) [ProtocolLib.jar:3.6.5-b222]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:268) [ProtocolLib.jar:3.6.5-b222]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at me.levansj01.verus.compat.v1_8_R3.PacketHandler.write(Unknown Source) [Verus.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327) [ProtocolLib.jar:3.6.5-b222]
	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345) [ProtocolLib.jar:3.6.5-b222]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [survival.jar:git-PaperSpigot-1f41387-9a17f01]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump
- [] If applicable, I have included a paste (not a screenshot) of the error
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**IMPORTANT: Follow the Checklist or we can't reproduce your issue and your issue will be close**

**Comment by FlorianMichael** [comment]
This shouldn't open on latest builds anymore. Please let us know if this issue is still persistent.
