### ISSUE TITLE
Hi I use mspigot 1.8.8 which is a fork of taco spigot . When I try to use viarewind this error comes

### ISSUE THREAD

**Issue by Shahed123456** [ViaVersion/ViaRewind#361]
[11:09:58 ERROR]: Could not load 'plugins/ViaRewind-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ViaVersion
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [server.jar:git-TacoSpigot-bf023c7d]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:286) [server.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [server.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:582) [server.jar:git-TacoSpigot-bf023c7d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Shahed123456** [comment]
meaning?

**Comment by PierreSchwang** [comment]
Viaversion is missing
