### ISSUE TITLE
bossbar cooldown config doesn't work

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/ViaRewind#409]
```
16:42:42 ERROR [Via-0] [STDERR] com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
16:42:42 ERROR [Via-0] [STDERR] Packet Type: null, Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous), Packet ID: -1
16:42:42 ERROR [Via-0] [STDERR] Caused by: java.io.IOException: Unable to read type JsonElement, found String
16:42:42 ERROR [Via-0] [STDERR]         at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:150)
16:42:42 ERROR [Via-0] [STDERR]         at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1.lambda$registerMap$0(PlayerPackets.java:52)
```

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
