### ISSUE TITLE
Players cannot join the game

### ISSUE THREAD

**Issue by 1983378984** [ViaVersion/ViaRewind#422]
### `/viaversion dump` Output

 https://dump.viaversion.com/fa2df30f3df0c9b43c8ffef12f0403b651c9246a75b3bfaaf1981ee3e33ccea0

### Console Error

1q2z3c4w_Web joined the game
[14:10:43 INFO]: 1q2z3c4w_Web[/112.101.100.156:37724] logged in with entity id 234270 at ([newworld1]67.79752295425254, 66.0, 64.37531876007561)
[14:10:43 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[14:10:43 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[14:10:43 WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[14:10:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[14:10:43 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:10:43 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:10:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:10:43 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[14:10:43 WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[14:10:43 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2649) + length(99) exceeds writerIndex(2695): PooledUnsafeDirectByteBuf(ridx: 2649, widx: 2695, cap: 4096)
[14:10:43 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[14:10:43 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[14:10:43 WARN]:        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:137)
[14:10:43 WARN]:        at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:133)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:381)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:36)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[14:10:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[14:10:43 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:10:43 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:10:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:10:43 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[14:10:43 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[14:10:43 WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[14:10:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[14:10:43 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:10:43 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:10:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:10:43 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[14:10:43 WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[14:10:43 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(47) + length(25) exceeds writerIndex(48): PooledUnsafeDirectByteBuf(ridx: 47, widx: 48, cap: 256)
[14:10:43 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[14:10:43 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[14:10:43 WARN]:        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.OptionalType.read(OptionalType.java:38)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:137)
[14:10:43 WARN]:        at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:134)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:381)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[14:10:43 WARN]:        at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:36)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[14:10:43 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[14:10:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[14:10:43 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[14:10:43 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[14:10:43 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[14:10:43 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[14:10:43 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[14:10:43 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:10:43 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:10:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:10:43 INFO]: 1q2z3c4w_Web lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[14:10:43 INFO]: 1q2z3c4w_Web left the game

### Bug Description

The player enters and then reports an error to exit the game, which occurs only in a moment

### Steps to Reproduce

Generated after using these plugins, not sure if there is a conflict
Below are screenshots of the installed plugins
![F(PA437 U`K Y0YHQ%6`569](https://user-images.githubusercontent.com/62001480/211134264-aaddbc83-baab-4bd9-84bc-bd87d11b3bc9.png)
![Q356VK~$TK EYC9UR5{7DSV](https://user-images.githubusercontent.com/62001480/211134265-92a55f03-f00b-4534-8d0c-1a1bec336bf8.png)
![$KK`SD{FFMGV 1LGF6UROHB](https://user-images.githubusercontent.com/62001480/211134266-7893ce0c-1194-4f17-bbe5-cfc12c2c4d7a.png)
![DU)2P4PPN%F@9}LJQH29}53](https://user-images.githubusercontent.com/62001480/211134267-69691841-1a41-4f9f-9c4c-990cbe9d69fd.png)
![EXSRR 7}Y(G4IR S64{%2%Y](https://user-images.githubusercontent.com/62001480/211134268-c7fe0a66-db15-4690-8af5-b18cb662188d.png)

### Expected Behavior

Resolving this error allows the server to access

### Additional Server Info

velocity geyser

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1886%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Purpur--1886%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by spookymgmt** [comment]
Ah yes, finally someone with the same error as me. Gl haha

**Comment by kennytv** [comment]
Without knowing how to reproduce this (i.e. narrowing down with what exact plugins/configurations this happens), there's not much we can do
