### ISSUE TITLE
java.lang.NoSuchMethodError: 'com.viaversion.viaversion.api.protocol.version.ProtocolVersion 

### ISSUE THREAD

**Issue by l3nnartt** [ViaVersion/ViaRewind#489]
### `/viaversion dump` Output

https://dump.viaversion.com/2fa4be216c5b4d69367bb44919a405c55920e90bee9fe4b56a6c7b7c7b31fb21

### Console Error

```
[00:14:58 WARN]: [ViaRewind-Legacy-Support] Task #67 for ViaRewind-Legacy-Support v1.5.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'com.viaversion.viaversion.api.protocol.version.ProtocolVersion com.viaversion.viaversion.api.protocol.version.ServerProtocolVersion.lowestSupportedProtocolVersion()'
	at com.viaversion.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:52) ~[ViaRewind-Legacy-Support-1.5.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
>....
```

### Bug Description

error spam

### Steps to Reproduce

use the newest plugin version

### Expected Behavior

ladders should work & no error spam

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.6-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.6--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Update viaversion and viabackwards to dev builds, viarewind-legacy-support does not function as intended with master builds.

**Comment by l3nnartt** [comment]
@Kichura the dev builds are newer than the latest master?

**Comment by l3nnartt** [comment]
seems to work, thx

**Comment by l3nnartt** [comment]
After updating it seems that 1.20 Clients cant use ladders and the movement ist "buggy"

**Comment by FlorianMichael** [comment]
War das davor auch schon kaputt oder erst seit dem Update?

**Comment by FlorianMichael** [comment]
Passiert das auch ohne ViaRewindLegacySupport?
