### ISSUE TITLE
Mapping errpr

### ISSUE THREAD

**Issue by terrarier2111** [ViaVersion/ViaRewind#492]
### `/viaversion dump` Output

https://dump.viaversion.com/5ef730d16e326086752f46dff69e9f825740a650f51b82d35f2be852af9ee213

### Console Error

```
02:18:42] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_15_2To1_16 IN REMAP OF ENTITY_EQUIPMENT (0x47)
[02:18:42] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02:18:42] [Netty Epoll Server IO #1/WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16$$Lambda$7316/0x00007f9038d79188
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.network.NetworkManager.c(NetworkManager.java:311)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.network.NetworkManager.lambda$9(NetworkManager.java:304)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:840)
[02:18:42] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02:18:42] [Netty Epoll Server IO #1/WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16$$Lambda$7316/0x00007f9038d79188
[02:18:42] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:172)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:117)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16.lambda$registerPackets$1(BlockItemPackets1_16.java:116)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.network.NetworkManager.c(NetworkManager.java:311)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.network.NetworkManager.lambda$9(NetworkManager.java:304)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:18:42] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:840)
[02:18:42] [Netty Epoll Server IO #3/INFO]: terrarier2111: CHUNK_BATCH_ACK
[02:18:42] [Netty Epoll Server IO #3/INFO]: terrarier2111: PLAYER_ROTATION
[02:18:42] [Server thread/INFO]: testingman45 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16$$Lambda$7316/0x00007f9038d79188
```

### Bug Description

1. client is on 1.12.2
2. client is on 1.20.4

2. client holds an item with a couple tags in the hand
1. client gets kicked with the error (and can't login thereafter)

### Steps to Reproduce

As above

### Expected Behavior

Don't get kicked

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: 4065--Spigot--e9ec548--06d9159%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-4065--Spigot--e9ec548--06d9159%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.7-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.7--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>
