### ISSUE TITLE
Unexplainable issue

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaRewind#531]
### `/viaversion dump` Output

 https://dump.viaversion.com/dc125de353b2ce2ece7cde4fc13a97e92c9b0a61ef24dfec92bd6e57633a9b62

### Console Error

```
JHarris lost connection: Internal Exception: io.netty.handler.codec.EncoderException: unable to fit 5001023 into 3
```

### Bug Description

I am on 1.20.4 (not sure what ver other players are on). When I teleport to a chunk I get kicked for the console error shown above. This has now prevented me from logging in. When I DO log in (changed my spawn location), my player data has been reset and the console has spammed this:

```
[22:44:48] [Profile Lookup Executor #1/WARN]: Couldn't look up profile properties for 5c84f71f-0245-4762-8e4c-9a6ad460d8b2
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read value <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>

<head>
    <meta content='text/html; charset=utf-8' http-equiv='content-type' />
    <style type='text/css'>
        body {
            font-family: Arial;
            margin-left: 40px;
        }

        img {
            border: 0 none;
        }

        #content {
            margin-left: auto;
            margin-right: auto
        }

        #message h2 {
            font-size: 20px;
            font-weight: normal;
            color: #000000;
            margin: 34px 0px 0px 0px
        }

        #message p {
            font-size: 13px;
            color: #000000;
            margin: 7px 0px 0px0px
        }

        #errorref {
            font-size: 11px;
            color: #737373;
            margin-top: 41px
        }
    </style>
    <title>Service unavailable</title>
</head>

<body>
    <div id='content'>
        <div id='message'>
            <h2>The request is blocked.</h2>
        </div>
        <div id='errorref'>
            <span>20240715T214448Z-15f86f5965dqk2vd39ww6rnbuw00000006v0000000002vtp            </span>
        </div>
    </div>
</body>
</html>

	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:32) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:99) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.52.jar:?]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fetchProfile(PaperMinecraftSessionService.java:35) ~[axolotl-1.20.4.jar:git-Axolotl-"228c3df"]
	at org.bukkit.craftbukkit.v1_20_R3.profile.CraftPlayerProfile.getUpdatedProfile(CraftPlayerProfile.java:141) ~[axolotl-1.20.4.jar:git-Axolotl-"228c3df"]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-6.0.52.jar:?]
	... 10 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-6.0.52.jar:?]
	... 10 more```

### Steps to Reproduce

No clue :(

### Expected Behavior

Doesnt do this

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by Barvalg** [comment]
![Platform: git--Axolotl--%22228c3df%22%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Axolotl--%22228c3df%22%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by JHarris12345** [comment]
As a 1.21 player joining, they get a more defined VV kick message:

```
[23:07:43] [Server thread/INFO]: princess_lyds lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_ENTITY_DATA, Type: Entity data list, Index: 2, Data: [{VarInt: 358407}], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$4 (Anonymous), Packet ID: 88```

**Comment by FlorianMichael** [comment]
First of all this is the wrong repository, also you need to actual provide FULL errors. You missed the most important part of the stack trace in your last message.
